### ISSUE TITLE
Can't get parameter: "teams" to work

### ISSUE THREAD

**Issue by ConverJens** [pozil/auto-assign-issue#119]
First of all, thanks for a great action!

I'm trying to use the teams parameter instead of assignees but it keeps on failing due to the token privileges. 

Could you specify exactly what permission that you are using for this to work? I'm using GitHub enterprise so it may be some other restriction on my part but it gets notoriously difficult to troubleshoot without know what a working token needs.

Thanks in advance!

**Comment by pozil** [comment]
Hi @ConverJens, you should only need the `read:org` scope as documented in the readme.

Could it be that:
- team visibility is private? I don't know if this has an impact but I have only tested with public teams.
- personal access tokens are [disabled per org policy](https://docs.github.com/en/organizations/managing-programmatic-access-to-your-organization/setting-a-personal-access-token-policy-for-your-organization)?
- you don't have the permission to edit the PR or issue in this job? You could try to manually specify
```yaml
permissions:
      issues: write
      pull-requests: write
```
