### ISSUE TITLE
Consider updating the `v1` tag on release

### ISSUE THREAD

**Issue by mskelton** [pozil/auto-assign-issue#13]
Currently, when using the action as specified in the readme, it points to the old version of this action on the `v1` tag.  The newer releases (e.g. `v1.0.4`) are not picked up automatically.  The solution is to update the v1 tag when releasing a new version in addition to publishing the full version.

Thankfully it's pretty simple with the following two commands after you release a version.  There are some GitHub actions out there that would probably do it as well if you are interested in that.

```sh
git tag -fa v1 -m "Update v1 tag"
git push origin v1 --force
```

**Comment by pozil** [comment]
Thx for the suggestion, I replaced the v1. I agree that it's probably not worth to have such a fine grained semver versioning for GH actions.

**Comment by mskelton** [comment]
@pozil I wouldn't say that specific versions are unnecessary as some people like to lock into a specific version.  Updating the tag is kind of like a `latest` tag in npm where it simply points to the latest version.  This is how GitHub structures all of the default actions:

<img width="785" alt="Screen Shot 2021-09-01 at 7 19 24 AM" src="https://user-images.githubusercontent.com/25914066/131670020-baaa8d24-9c72-49a0-869f-24fc57e097bf.png">
