### ISSUE TITLE
Assign single reviewer

### ISSUE THREAD

**Issue by jtodev** [pozil/auto-assign-issue#147]
Hello, my team would like to use this action for assigning a random assignee and a random reviewer to incoming PRs.

#### Issue
As far as I see, it is possible with this action to assign a single assignee different from the author to an incoming PR. But after that the whole team (excluding the author) is assigned as the reviewers. We would like there to be only one person or a set number  people different form the author and the assignee being set as reviewer(s).

We would be very grateful if you were to implement a change that would allow this. And frankly I think that the addition of a `numOfReviewer` parameter would a nice complement to the `numOfAssignee` parameter.

**Comment by pozil** [comment]
Hi @jtodev, thanks for reaching out. As you pointed out, there's no `numOfReviewer` parameter at the moment but despite it's name the `numOfAssignee` parameter serves this exact purpose when the action is running in the context of a PR.

Say you have a team of two assigned via `teams` and that you have `numOfAssignee` set to `1`, the action will pick a random team member as a reviewer provided that they are not the PR author.
I added a test for this behavior [here](https://github.com/pozil/auto-assign-issue/blob/v2/src/__tests__/action.test.js#L333).

Does it make sense?
