### ISSUE TITLE
Assignation doesn't work for PRs

### ISSUE THREAD

**Issue by agomezmoron** [pozil/auto-assign-issue#52]
When using the action with a PR it doesn't work.

PRs have assignees and requested_reviewers. IMHO, assignees in the PR context should be a requested_reviewer - and the same to remove the previous ones.

**Comment by agomezmoron** [comment]
I am working on a PR to provide a fix but I have pending the tests https://github.com/pozil/auto-assign-issue/pull/51

**Comment by pozil** [comment]
Thanks for taking a look into this. I must admit that I haven't tested the behavior of the action on PRs.
I generally don't use assignees so I agree on switching to reviewers.

**Comment by pozil** [comment]
Thanks for the fix, I'll release a new version with your work.
