### ISSUE TITLE
Allow 0 Assignees

### ISSUE THREAD

**Issue by codyhod** [pozil/auto-assign-issue#58]
More of a feature request; and happy to take a stab at it myself if you think it's not worth the time spent.

It would be nice to be able to set the number of assignees to 0, coupled with the remove existing assignee flag this would allow issues to be completely unassigned.

My use case for context:
When an issue is created with a certain label, move the issue to backlog automatically and remove all assignees.

**Comment by pozil** [comment]
Hi @codyhod and thanks for the suggestion. This is a good use case. I've implemented it and released it in v1.8.0.
