### ISSUE TITLE
Option to Not Assign If Issue already has Assignees

### ISSUE THREAD

**Issue by filipemiguelrocha** [pozil/auto-assign-issue#76]
Greetings!

I'm implementing this action in my organization with some other functions for a triage procedure and there are certain cases where we don't want the workflow to assign new people if it already has people assigned. 

This also appears to happen by itself if we make the workflow work with `labeled` and `unlabeled` triggers. Even it it was the action that assigned the users, it will assign two new random users from the team.

Therefore, I wanted to know if it's possible to create an option to not assign if it already has assignees. That would work good for issues that are being relabeled or reopened that trigger our workflow without having to hardcode conditions that would make our process harder in combination with everything else we have running.

The option to `removePreviousAssignees` doesn't quite do the job for us in this regard since we don't want it to be rotating. 

Thanks in advance

**Comment by pozil** [comment]
Hi @filipemiguelrocha thanks for reaching out. This is a good use case.
I'll work on adding an `abortIfPreviousAssignees` flag.

**Comment by pozil** [comment]
Done. I added this feature to a refactoring that I had planned earlier.
