### ISSUE TITLE
Assign reviewers when PR is not draft

### ISSUE THREAD

**Issue by mariajgrimaldi** [pozil/auto-assign-issue#92]
Hello there! 

I recently updated one of my workflows from v1.5.0 to the latest version of this action and found out that now assignees are also tagged as reviewers, which is pretty nice. The issue is, should they be tagged when the PR is still draft?

**Comment by pozil** [comment]
Hi @mariajgrimaldi. For this kind of use case, I would use a filter in the workflow so that the action doesn't run for draft PRs like this:
https://github.com/orgs/community/discussions/25722

Would this work?
